server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    dbc-url: jdbc:mariadb://localhost:3306/board_prac
    username: root
    password: root
    tomcat:
      max-wait: 10000
      time-between-eviction-runs-millis: 30000
      validation-query: select 1
      validation-query-timeout: 5
      test-while-idle: true
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update